### PR TITLE
Added instructions for migrating to MatFileRW, if people want to.

### PR DESCRIPTION
**Pull request by nedtwigg**

### CODE REVIEW

**Comment by codemercenary** [comment]
Delete your fork, I'll transfer ownership of this repo to you.

**Comment by nedtwigg** [comment]
Roger, deleted.  Thanks Jason.

**Comment by codemercenary** [comment]
It's all yours.  Take good care of it.

**Comment by nedtwigg** [comment]
I'll keep it warm for you :+1:

**Pull request merged**
